import os
from supabase import create_client


class SupabaseClient:
    
    def __init__(self):
        self.client_url = os.environ.get("SUPABASE_URL")
        self.key = os.environ.get("SUPABASE_KEY")
        self.supabase = create_client(self.client_url, self.key)
        # self.create_table_for_fmp()
    
    '''
    on db side is needed a helfunction:
        create or replace function public.exec_sql(sql text)
        returns void
        language plpgsql
        as $$
        begin
        execute sql;
        end;
        $$;
    '''
    
    # def create_table_for_fmp(self) -> None:
    #     sql = """
    #         create table if not exists public.fmp_table (
    #             id bigint generated by default as identity primary key,
    #             symbol text not null,
    #             date date not null,
    #             eps_actual double precision,
    #             eps_estimated double precision,
    #             revenue_actual bigint,
    #             revenue_estimated bigint,
    #             last_updated timestamptz not null default timezone('utc'::text, now()),
    #             call_date timestamptz not null,
    #             active integer not null default 0
    #         );
    #     """
    #     try:
    #         self.supabase.postgrest.rpc("exec_sql", {"sql": sql})
    #     except Exception as e:
    #         # Error log
    #         pass

    def insert_earning_report(
        self,
        symbol,
        date,
        eps_actual,
        eps_estimated,
        revenue_actual,
        revenue_estimated,
        last_updated,
        call_date,
        active
        ):
        try:
            response = (
                self.supabase.table("fmp_table")
                .insert({
                    "symbol": symbol,
                    "date": date,
                    "eps_actual": eps_actual,
                    "eps_estimated": eps_estimated,
                    "revenue_actual": revenue_actual,
                    "revenue_estimated": revenue_estimated,
                    "last_updated": last_updated,
                    "call_date": call_date,
                    "active": active
                })
                .execute()
            )
        except Exception as e:
            print("Doppelter Eintrag")
        return response
